# Generated by Django 4.2.2 on 2024-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
