# Generated by Django 4.2.2 on 2024-06-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievementcompletion',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='achievements.achievement'),
        ),
        migrations.AlterField(
            model_name='achievementcompletion',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='completions', to='achievements.player'),
        ),
    ]
