# Generated by Django 4.2.2 on 2024-06-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_team_points_alter_achievementcompletion_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(max_length=32),
        ),
    ]
