# Generated by Django 4.2.2 on 2024-06-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_achievement_description_alter_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='beatmap_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
