# Generated by Django 4.2.2 on 2024-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_beatmapinfo_remove_achievement_beatmap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
