# Generated by Django 4.2.2 on 2024-06-09 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_remove_mappool_mappack_tournamentround_mappack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvolvement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to=settings.AUTH_USER_MODEL),
        ),
    ]
